name: Assign Issue

on:
  issues:
    types: [opened, labeled, unlabeled, edited, reopened]

permissions:
  issues: write

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Issue to Creator
        if: github.event.issue.body.includes('Would you like to work on this issue?') && github.event.issue.body.includes('Yes')
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
            -d '{"assignees":["${{ github.event.issue.user.login }}"]}'

      - name: Assign Issue on Comment
        if: github.event.comment.body == '/assign'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
            -d '{"assignees":["${{ github.event.comment.user.login }}"]}'

      - name: Update Labels
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
            -d '{"labels":["Status: Assigned"]}'
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/up-for-grabs

      - name: Set Timeline
        run: |
          if [[ "${{ github.event.issue.labels }}" == *"priority: high"* ]]; then
            echo "3 days"
          elif [[ "${{ github.event.issue.labels }}" == *"priority: medium"* ]]; then
            echo "6 days"
          elif [[ "${{ github.event.issue.labels }}" == *"priority: low"* ]]; then
            echo "8 days"
          fi
