name: Unassigned Issue Priority Tracking

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute

permissions:
  issues: write

jobs:
  track-unassigned-priority:
    runs-on: ubuntu-latest
    steps:
      - name: Check Unassigned Issues for Priority Labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
            });

            const now = new Date();
            console.log(`Current time: ${now}`);

            for (const issue of issues) {
              if (issue.assignees.length > 0) continue; // Only process unassigned issues

              const createdAt = new Date(issue.created_at);
              const labels = issue.labels.map(l => l.name);

              const elapsedMinutes = Math.floor((now - createdAt) / 60000); // Time since issue creation

              console.log(`Issue #${issue.number} | Created: ${createdAt} | Time elapsed: ${elapsedMinutes} min`);

              // Apply priority labels at correct intervals
              if (elapsedMinutes >= 1 && !labels.includes("priority: low")) {
                console.log(`🔹 Adding "priority: low" label to Issue #${issue.number}`);
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: ["priority: low"]
                });
              }

              if (elapsedMinutes >= 2 && !labels.includes("priority: medium")) {
                console.log(`🔹 Adding "priority: medium" label to Issue #${issue.number}`);
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: ["priority: medium"]
                });
              }

              if (elapsedMinutes >= 3 && !labels.includes("priority: high")) {
                console.log(`🔹 Adding "priority: high" label to Issue #${issue.number}`);
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: ["priority: high"]
                });
              }
            }
