name: Unassigned Issue Priority Tracking

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute

permissions:
  issues: write

jobs:
  track-unassigned-priority:
    runs-on: ubuntu-latest
    steps:
      - name: Check Unassigned Issues for Priority Labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
            });

            const now = new Date();
            console.log(`Current time: ${now}`);

            for (const issue of issues) {
              if (issue.assignees.length) continue; // Skip assigned issues

              const createdAt = new Date(issue.created_at);
              const labels = issue.labels.map(l => l.name);

              let deadlineMinutes = 3; // Max deadline
              const deadline = new Date(createdAt.getTime() + deadlineMinutes * 60000);
              const timeLeft = Math.floor((deadline - now) / 60000); // Minutes remaining

              console.log(`Issue #${issue.number} | Created: ${createdAt} | Deadline: ${deadline} | Time left: ${timeLeft} min`);

              // Add labels based on time left
              if (timeLeft === 2 && !labels.includes("priority: low")) {
                console.log(`🔹 Adding "priority: low" label to Issue #${issue.number}`);
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: ["priority: low"]
                });
              }

              if (timeLeft === 1 && !labels.includes("priority: medium")) {
                console.log(`🔹 Adding "priority: medium" label to Issue #${issue.number}`);
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: ["priority: medium"]
                });
              }

              if (timeLeft === 0 && !labels.includes("priority: high")) {
                console.log(`🔹 Adding "priority: high" label to Issue #${issue.number}`);
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: ["priority: high"]
                });
              }
            }
